Traceback (most recent call last):
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/spr/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
directory = 'FITS_files/'
filename = 'ucmP_0052.fits'
imagen = fits.getdata(directory+filename)
header = fits.getheader(directory+filename)
exposure = header['EXPTIME']
print(header['FILENAME'],header['OBJECT'],
      header['INSFLNAM'],header['EXPTIME'],
      int(np.mean(imagen)),int(np.std(imagen)),
      np.min(imagen), np.max(imagen))

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-3-8683502edec9>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mdirectory[0m [0;34m=[0m [0;34m'FITS_files/'[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mfilename[0m [0;34m=[0m [0;34m'ucmP_0052.fits'[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mimagen[0m [0;34m=[0m [0mfits[0m[0;34m.[0m[0mgetdata[0m[0;34m([0m[0mdirectory[0m[0;34m+[0m[0mfilename[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mheader[0m [0;34m=[0m [0mfits[0m[0;34m.[0m[0mgetheader[0m[0;34m([0m[0mdirectory[0m[0;34m+[0m[0mfilename[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mexposure[0m [0;34m=[0m [0mheader[0m[0;34m[[0m[0;34m'EXPTIME'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/io/fits/convenience.py[0m in [0;36mgetdata[0;34m(filename, header, lower, upper, view, *args, **kwargs)[0m
[1;32m    192[0m     [0mmode[0m[0;34m,[0m [0mclosed[0m [0;34m=[0m [0m_get_file_mode[0m[0;34m([0m[0mfilename[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    193[0m [0;34m[0m[0m
[0;32m--> 194[0;31m     [0mhdulist[0m[0;34m,[0m [0mextidx[0m [0;34m=[0m [0m_getext[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    195[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    196[0m         [0mhdu[0m [0;34m=[0m [0mhdulist[0m[0;34m[[0m[0mextidx[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/io/fits/convenience.py[0m in [0;36m_getext[0;34m(filename, mode, ext, extname, extver, *args, **kwargs)[0m
[1;32m   1052[0m         [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0;34m'extver alone cannot specify an extension.'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1053[0m [0;34m[0m[0m
[0;32m-> 1054[0;31m     [0mhdulist[0m [0;34m=[0m [0mfitsopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0mmode[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1055[0m [0;34m[0m[0m
[1;32m   1056[0m     [0;32mreturn[0m [0mhdulist[0m[0;34m,[0m [0mext[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py[0m in [0;36mfitsopen[0;34m(name, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)[0m
[1;32m    162[0m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34mf'Empty filename: {name!r}'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    163[0m [0;34m[0m[0m
[0;32m--> 164[0;31m     return HDUList.fromfile(name, mode, memmap, save_backup, cache,
[0m[1;32m    165[0m                             lazy_load_hdus, **kwargs)
[1;32m    166[0m [0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py[0m in [0;36mfromfile[0;34m(cls, fileobj, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)[0m
[1;32m    399[0m         """
[1;32m    400[0m [0;34m[0m[0m
[0;32m--> 401[0;31m         return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
[0m[1;32m    402[0m                              [0msave_backup[0m[0;34m=[0m[0msave_backup[0m[0;34m,[0m [0mcache[0m[0;34m=[0m[0mcache[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    403[0m                              lazy_load_hdus=lazy_load_hdus, **kwargs)

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py[0m in [0;36m_readfrom[0;34m(cls, fileobj, data, mode, memmap, cache, lazy_load_hdus, **kwargs)[0m
[1;32m   1050[0m             [0;32mif[0m [0;32mnot[0m [0misinstance[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0m_File[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1051[0m                 [0;31m# instantiate a FITS file object (ffo)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1052[0;31m                 [0mfileobj[0m [0;34m=[0m [0m_File[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0mmode[0m[0;34m,[0m [0mmemmap[0m[0;34m=[0m[0mmemmap[0m[0;34m,[0m [0mcache[0m[0;34m=[0m[0mcache[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1053[0m             [0;31m# The Astropy mode is determined by the _File initializer if the[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1054[0m             [0;31m# supplied mode was None[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/utils/decorators.py[0m in [0;36mwrapper[0;34m(*args, **kwargs)[0m
[1;32m    533[0m                     [0mwarnings[0m[0;34m.[0m[0mwarn[0m[0;34m([0m[0mmessage[0m[0;34m,[0m [0mwarning_type[0m[0;34m,[0m [0mstacklevel[0m[0;34m=[0m[0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    534[0m [0;34m[0m[0m
[0;32m--> 535[0;31m             [0;32mreturn[0m [0mfunction[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    536[0m [0;34m[0m[0m
[1;32m    537[0m         [0;32mreturn[0m [0mwrapper[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/io/fits/file.py[0m in [0;36m__init__[0;34m(self, fileobj, mode, memmap, overwrite, cache)[0m
[1;32m    173[0m             [0mself[0m[0;34m.[0m[0m_open_fileobj[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0moverwrite[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    174[0m         [0;32melif[0m [0misinstance[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0;34m([0m[0mstr[0m[0;34m,[0m [0mbytes[0m[0;34m)[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 175[0;31m             [0mself[0m[0;34m.[0m[0m_open_filename[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0moverwrite[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    176[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    177[0m             [0mself[0m[0;34m.[0m[0m_open_filelike[0m[0;34m([0m[0mfileobj[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0moverwrite[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/io/fits/file.py[0m in [0;36m_open_filename[0;34m(self, filename, mode, overwrite)[0m
[1;32m    562[0m [0;34m[0m[0m
[1;32m    563[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_try_read_compressed[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mname[0m[0;34m,[0m [0mmagic[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0mext[0m[0;34m=[0m[0mext[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 564[0;31m             [0mself[0m[0;34m.[0m[0m_file[0m [0;34m=[0m [0mfileobj_open[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mname[0m[0;34m,[0m [0mIO_FITS_MODES[0m[0;34m[[0m[0mmode[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    565[0m             [0mself[0m[0;34m.[0m[0mclose_on_error[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m
[1;32m    566[0m [0;34m[0m[0m

[0;32m~/Documentos/Docencia/TEA/teaenv/lib64/python3.8/site-packages/astropy/io/fits/util.py[0m in [0;36mfileobj_open[0;34m(filename, mode)[0m
[1;32m    390[0m     """
[1;32m    391[0m [0;34m[0m[0m
[0;32m--> 392[0;31m     [0;32mreturn[0m [0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0mbuffering[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    393[0m [0;34m[0m[0m
[1;32m    394[0m [0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'FITS_files/ucmP_0052.fits'
FileNotFoundError: [Errno 2] No such file or directory: 'FITS_files/ucmP_0052.fits'

